version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - ./:/usr/app/
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env.development
    expose:
      - '8080'
    ports:
      - '8080:3000'
    container_name: tasks-api
    entrypoint: ./development-entry.sh
    command: [/usr/app/development-entry.sh]
    depends_on:
      - db
  db:
    image: mysql:5.7
    expose:
      - '3306'
    ports:
      - '3306:3306'
    env_file:
      - ./.env.development
    volumes:
      - db_data:/var/lib/mysql
    container_name: tasks-db
volumes:
  db_data: {}
